### ISSUE TITLE
Building with restish as a library dependency fails when CGO_ENABLED=0

### ISSUE THREAD

**Issue by rohitkothari** [rest-sh/restish#320]
## Description

Projects that import restish as a library cannot build with CGO_ENABLED=0 since v0.21.0. The unconditional import of `github.com/ThalesIgnite/crypto11` in `cli/request.go` pulls in `github.com/miekg/pkcs11`, which defines its core types in CGo files. When CGo is disabled, those types are excluded and compilation fails:

```
# github.com/ThalesIgnite/crypto11
crypto11.go:127:16: undefined: pkcs11.ObjectHandle
crypto11.go:174:14: undefined: pkcs11.Ctx
crypto11.go:177:16: undefined: pkcs11.TokenInfo
sessions.go:34:17: undefined: pkcs11.Ctx
...
```

This affects any consumer like us that embeds restish and cross-compiles with CGO_ENABLED=0. The previous versions up to v0.20.0 did not have this dependency and built cleanly without CGo.

## Question

Would it be feasible to put the PKCS#11 functionality behind a build tag so that it's opt-in? That way library consumers who don't need hardware token support can continue building without CGo, while users who need PKCS#11 can enable it explicitly.

**Comment by danielgtaylor** [comment]
Thanks for the report. I re-checked this against v2.0.0, and the PKCS#11 code has been split out into the separate `restish-pkcs11` plugin command instead of being pulled into the main CLI/library path.

I verified the main v2 CLI builds with CGO disabled:

```sh
CGO_ENABLED=0 go build ./cmd/restish
```

That build succeeds. The remaining `crypto11` imports are isolated under `cmd/restish-pkcs11`, so consumers that do not build that plugin should not pull in the CGO-only PKCS#11 implementation.

Please give v2 a try. If you still hit a CGO build failure while importing the v2 library path or building the main CLI, please open a fresh issue with the import path and build command.
